---

version: 1

build_arg_defaults:
  EE_BASE_IMAGE: "quay.io/ansible/ansible-runner:stable-2.12-latest"
  EE_BUILDER_IMAGE: "ghcr.io/cloudera-labs/ansible-builder:${BUILD_TAG:-latest}"

dependencies:
  galaxy: requirements.yml
