---

name: Test

on:
  push:
  pull_request:
    types: [labeled]
  workflow_dispatch:
    
jobs:
  build:
    if: github.event.label.name == 'test' || github.event_name == 'workflow_dispatch'
    uses: wmudge/cldr-runner/.github/workflows/build_and_push_image.yml@feature/builder-ex-env
    with:
      EE_CONTEXT_FOLDER: ./

  # Remove/reset label if invoked by the appropriate 'labeled' event
  remove-label:
    if: github.event.label.name == 'test'
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: |
            test

  test:
    needs: build
    runs-on: ubuntu-latest
    container: ${{ needs.build.outputs.image-sha }}
    steps:
      - run: ansible --version >> $GITHUB_OUTPUT
      - run: ansible-galaxy collection list >> $GITHUB_OUTPUT
