---

name: Preliminary tests

on:
  pull_request:
  workflow_dispatch:
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - run: |
          apt-get -y update
          apt-get -y install python3 python3-pip
          update-alternatives --install /usr/bin/python python $(which python3) 1
          pip install ansible-core==2.12 ansible-builder 
          ansible-galaxy collection install -r builder/requirements.yml

      - run: ansible --version
      - run: ansible-galaxy collection list
      - run: |
          ansible-builder introspect --write-pip final_python.txt --write-bindep final_bindep.txt
          pip install -r final_python.txt
          apt -y install $(cat final_bindep.txt)
      - run: pip freeze
