---

name: Test

on:
  push:
  pull_request:
    types: [labeled]
  workflow_dispatch:
    inputs:
    
jobs:
  test:
    runs-on: ubuntu-latest
    container: quay.io/ansible/ansible-runner:stable-2.12-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - run: apt-get -y install buildah
      - run: pip install ansible-builder==1.2.0
      - run: ansible --version
      - run: ansible-galaxy collection install -r requirements.yml
      - run: ansible-galaxy collection list
      - run: ansible-builder introspect --sanitize --user-pip=requirements.txt --user-bindep=bindep.txt --write-bindep=/tmp/src/bindep.txt --write-pip=/tmp/src/requirements.txt
      - run: echo $(cat /tmp/src/bindep.txt)
      - run: echo $(cat /tmp/src/requirements.txt)

      - name: Construct image metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            type=sha
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Construct short SHA
        id: sha
        run: echo "sha-short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          context: .
          image: ${{ github.repository }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          containerfiles: |
            ./Containerfile

      - name: Push image
        id: push-image
        uses: redhat-actions/push-to-registry@v2
        with:
          tags: ${{ steps.meta.outputs.tags }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

  # Remove/reset label if invoked by the appropriate 'labeled' event
  remove-label:
    if: github.event.label.name == 'test'
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: |
            test
